### ISSUE TITLE
LightGraphs dependency

### ISSUE THREAD

**Issue by jtrakk** [JuliaGraphs/GraphDataFrameBridge.jl#20]
I think LightGraphs.jl has been renamed to Graphs.jl but GraphDataFrameBridge still depends on LightGraphs.

**Comment by nickeubank** [comment]
Sure enough! I will admit my research is taking me away from the julia network analysis ecosystem for little while, so if you are amenable to submitting a pull request that updates things appropriately I would be delighted to merge it! Otherwise I'll leave this as a to do for when I have a little bit more time to figure out where things stand.

**Comment by ljournot** [comment]
An additional issue when also using `MetaGraphs.` Adding `GraphDataFrameBridge` is preventing installing `MetaGraphs v0.7.1` and imposes `v0.6.8`, which depends on `LightGraphs`, which in turn is causing trouble when working with `Graphs`.
As I am a newbie, a biologist (and even worse, French), I am afraid I won't be  of any help but I'll be happy to go on using `GraphDataFrameBridge` when it'll be fixed.

**Comment by nickeubank** [comment]
OK, should be all good! Would y'all mind updating your installations and seeing if it all works for you now?

**Comment by nickeubank** [comment]
(New version is v0.3.0)

**Comment by jtrakk** [comment]
Yes that works for me, thanks!

**Comment by ljournot** [comment]
It's ok with me too. Thanks a lot!
